project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Data Science with Python"
  author: "Thilo Kraft & Jan Bischoff"
  date: "July 28, 2023"
  # description: "A one-day workshop introducing you to the Python programming language for Data Science"
  chapters:
    - index.qmd
    - 01-introduction-to-python.qmd
    - 02-fundamentals-of-python.qmd
    - 03-data-wrangling-visualization.qmd
    - 04-advanced-visualization-modeling.qmd
    - 99-next-steps.qmd
  # logo: files/logo.png
  # sidebar:
  #   tools:
  #     - icon: box-arrow-up-right
  #       href: https://lukas-juergensmeier.com/
github-repo: coding-intro/intro-python-2023-07

#bibliography: references.bib

format:
  html:
    css: [css/custom-environments.css, css/fontawesome/css/all.css]
    theme: cosmo



